# Generated by Django 4.2.13 on 2024-06-12 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Home", "Home"),
                            ("Education", "Education"),
                            ("Personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interest_rate", models.FloatField()),
                ("term_period", models.IntegerField()),
                ("disbursement_date", models.DateField()),
                (
                    "loan_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("emi_dates", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_user_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aadhar_id", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credit_score", models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loanapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loans.user"
            ),
        ),
    ]
